### PR TITLE
BUG: fix sphinx build command

### PR DESCRIPTION
**Pull request by pv**
Sorry, forgot that the sphinx build command requires an in-place build first.
Here's a fixed version.

### CODE REVIEW

**Comment by pv** [comment]
Annoyingly, the fact that this is a `scikits` sub-package makes the installed version override the version.

**Comment by rc** [comment]
With this fix the gh-pages seem to be the same as before, and looking good - I guess it worked ok for me before the fix. What is the problem with the version?

Ready to merge, if you say so :)

**Comment by pv** [comment]
You may have had scikits.umfpack installed, or had an existing in-place
build, so it worked. (The problem is 'python setup.py install'-ed
version overriding the in-place built version.)
.
Anyway this PR makes things better in case there's no version installed.

**Comment by rc** [comment]
I see, thanks for the explanation. Let's merge it.

**Pull request merged**
