### PR TITLE
Readme Improvements

### PR DESCRIPTION
**Pull request by timtadh**
1. Changed to markdown format
2. Added an extension so that github renders it
3. Added instructions for SuiteSparse

I am not married to the markdown format. I considered keeping it in
restructured text. The reason I changed it is markdown just works a
little bit smoother with github.

I also added instructions for SuiteSparse which tripped me up initially.

### CODE REVIEW

**Comment by rc** [comment]
Thank you, besides my comment above, it seems ok.

I would only suggest using the commit message style that @pv uses, i.e. something like:

```
DOC: change README format to markdown, add SuiteSparse instructions
...
```

The other comments in the message can stay as they are, of course.

**Comment by timtadh** [comment]
@rc I made the changes you suggested. I will additionally add `BUG:` to the commit messages on the other prs.

**Comment by rc** [comment]
Thanks, it is in!

**Comment by rc** [comment]
BTW. I missed that README is used in setup.py - fixed by a17138cc8fdb8702a4863e9ac03604010c47c54c.

**Pull request merged**
