### PR TITLE
BUG: fix README formatting on PyPi by using pandoc

### PR DESCRIPTION
**Pull request by rc**

### CODE REVIEW

**Comment by rc** [comment]
Both test PyPi (https://testpypi.python.org/pypi/scikit-umfpack/0.0c) and github formatting now seems OK. Can anyone verify? (@timtadh)

**Comment by timtadh** [comment]
@rc . Looks legit. You should add a note about installing pandoc for creating distribution packages to the README. It looks like it was a good way to go!

**Comment by rc** [comment]
@timtadh, as it is not needed for normal use, I would rather put the info about pandoc into the release.rst, see #14.

**Comment by timtadh** [comment]
@rc good idea. :shipit: :+1:

**Pull request merged**
