### PR TITLE
Docs release tasks

### PR DESCRIPTION
**Pull request by rc**
Instructions what to do when making a release.

### CODE REVIEW

**Comment by rc** [comment]
@timtadh So pypandoc is mentioned here.

It would be great if someone could verify that the above instructions work. On testpypi only, of course :) You might need to tweak the project name in setup.py, as scikit-umfpack already exists there...

**Comment by timtadh** [comment]
@rc ok i will do that. might not get to it today as it is pretty crazy. If i forget about it ping me.

**Comment by rc** [comment]
@timtadh ping :)

**Comment by timtadh** [comment]
ok taking a look. Sorry for the delay.

**Comment by timtadh** [comment]
@rc The only problem I see is

    running sdist
    running check
    warning: sdist: standard file not found: should have one of README, README.txt

Which means the `.rst` README isn't going into the sdist. I don't think it is a big problem but just FYI.

Everything else seems good.

**Comment by rc** [comment]
Thank you for trying that out. The README.md is included, as it is listed in MANIFEST.in. So I guess it can be merged.

**Comment by timtadh** [comment]
:+1:

**Pull request merged**
